name: Update sub-web

on:
  push:
    branches:
      - main
    paths:
      - "!docs/**"
  workflow_dispatch:
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  # è‡ªåŠ¨å–æ¶ˆå…¶ä»–è¿è¡Œä¸­çš„workflow
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      ui-version: ${{ steps.web.outputs.ui-ver }}
    env:
      GIT_TOKEN: ${{secrets.REPO_TOKEN}}
    steps:
      - name: Setup timezone
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "Asia/Shanghai"
      - name: Sync commit
        uses: actions/checkout@v5
        with:
          token: ${{env.GIT_TOKEN}}
      - name: Check sub-web commit
        id: web
        run: |
          cd $GITHUB_WORKSPACE
          echo "ui-ver=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Use Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "latest"
      - name: Get dependencies and build
        run: |
          npm install -g pnpm@latest-10
          pnpm install
          pnpm run build
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
      - name: Push to Cloudflare Pages
        run: |
          cd $GITHUB_WORKSPACE
          sudo rm -rf docs
          mkdir docs
          mv dist/* docs
          sed -i 's/cloudflare_analytics_token/50c2fe99a72d4537884ce5951738ec23/' docs/index.html
          sudo rm -rf sub-web/*
      - name: Update sub-web
        uses: EndBug/add-and-commit@v9
        with:
          author_email: mail@example.com
          default_author: github_actions
          message: "Updated cloudflare pages to commit ${{ steps.web.outputs.ui-ver }} ðŸŽ‰ "
          add: "-A"
        env:
          token: ${{env.GIT_TOKEN}}
      - name: Push to GithubCI
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: actions/github-script@v8
        with:
          github-token: ${{env.GIT_TOKEN}}
          script: |
            github.rest.actions.createWorkflowDispatch({
            owner: context.repo.owner,
            repo: 'sub-web',
            workflow_id: 'build.yml',
            ref: 'main',
            });

#  build-changelog:
#    needs: prepare
#    runs-on: ubuntu-latest
#    env:
#      GIT_TOKEN: ${{secrets.ACTIONS_TOKEN}}
#      UI-VERSION: ${{ needs.prepare.outputs.ui-version }}
#    steps:
#      - name: Setup timezone
#        uses: hoang-rio/set-timezone@v1.4
#        with:
#          timezoneLinux: "Asia/Shanghai"
#      - uses: actions/checkout@v5
#        with:
#          fetch-depth: 0
#          token: ${{env.GIT_TOKEN}}
#      - name: Build CHANGELOG
#        id: build_changelog
#        uses: mikepenz/release-changelog-builder-action@v3.6.0
#        with:
#          configurationJson: |
#            {
#                "template": "## *** ðŸ“œ CHANGELOG ðŸ“œ ***\n\n#${{steps.build_changelog.outputs.changelog}}\n\n<details>\n<summary>Uncategorized</summary>\n\n#{{UNCATEGORIZED}}\n</details>",
#                "empty_content": "## *** ðŸ“œ CHANGELOG ðŸ“œ ***\n\n### Just have fun, nothing has changed.\n### * PS: The submodule sub-web'version is ${{ env.UI-VERSION }}",
#                "categories": [
#                    {
#                        "title": "## ðŸš€ Features",
#                        "labels": ["feature"],
#                        "empty_template": "No Features, No Bug ðŸŽ‰ ðŸŽ‰ ðŸŽ‰ "
#                    },
#                    {
#                        "title": "## ðŸ› Fixes",
#                        "labels": ["fix"]
#                    }
#                ],
#                "label_extractor": [
#                    {
#                        "pattern": "(.) (.+)",
#                        "target": "$1",
#                        "flags": "gu"
#                    },
#                    {
#                        "pattern": "\\[Issue\\]",
#                        "on_property": "title",
#                        "method": "match"
#                    }
#                ],
#                "duplicate_filter": {
#                    "pattern": "\\[ABC-....\\]",
#                    "on_property": "title",
#                    "method": "match"
#                },
#                "transformers": [
#                    {
#                        "pattern": "[\\-\\*] (\\[(...|TEST|CI|SKIP)\\])( )?(.+?)\n(.+?[\\-\\*] )(.+)",
#                        "target": "- $4\n  - $6"
#                    }
#                ],
#                "max_tags_to_fetch": 10,
#                "max_pull_requests": 40,
#                "max_back_track_time_days": 90
#            }
#          ignorePreReleases: "false"
#          owner: LM-Firefly
#          repo: subconverter
#          outputFile: "$GITHUB_WORKSPACE/CHANGELOG.md"
#          token: ${{ env.GIT_TOKEN }}

#      - name: Insert Changelog
#        run: |
#          echo "${{steps.build_changelog.outputs.changelog}}" >> $GITHUB_WORKSPACE/CHANGELOG.md
#      - uses: actions/checkout@v5
#        with:
#          fetch-depth: 0
#          token: ${{env.GIT_TOKEN}}
#      - name: Insert Changelog
#        uses: EndBug/add-and-commit@v9.1.4
#        with:
#          author_email: mail@example.com
#          default_author: github_actions
#          message: "Updated CHANGELOG.md"
#          add: "-A"
#        env:
#          token: ${{env.GIT_TOKEN}}
#  generate-changelog:
#    needs: prepare
#    runs-on: ubuntu-latest
#    env:
#      GIT_TOKEN: ${{secrets.ACTIONS_TOKEN}}
#    steps:
#      - name: Setup timezone
#        uses: hoang-rio/set-timezone@v1.4
#        with:
#          timezoneLinux: "Asia/Shanghai"
#      - uses: actions/checkout@v5
#        with:
#          fetch-depth: 0
#          token: ${{env.GIT_TOKEN}}
#      - uses: BobAnkh/auto-generate-changelog@v1.2.4
#        with:
#          REPO_NAME: "LM-Firefly/subconverter"
#          ACCESS_token: ${{env.GIT_TOKEN}}
#          PATH: "$GITHUB_WORKSPACE/CHANGELOG.md"
#          COMMIT_MESSAGE: "update release notes"
#          TYPE: "feat:Feature,fix:Bug Fixes,docs:Documentation,refactor:Refactor,perf:Performance Improvements"
#          REGENERATE_COUNT: 1

#  changelog-ci:
#    needs: prepare
#    runs-on: ubuntu-latest
#    env:
#      GIT_TOKEN: ${{secrets.ACTIONS_TOKEN}}
#      VER: ${{ needs.prepare.outputs.ver }}
#    steps:
#      - name: Setup timezone
#        uses: hoang-rio/set-timezone@v1.4
#        with:
#          timezoneLinux: "Asia/Shanghai"
#      - uses: actions/checkout@v5
#        with:
#          fetch-depth: 0
#          token: ${{env.GIT_TOKEN}}
#      - uses: saadmk11/changelog-ci@v1.1.1
#        with:
#          changelog_filename: "$GITHUB_WORKSPACE/CHANGELOG.md"
#          changelog_type: "commit_message"
#          release_version: ${{ env.VER }}
#          github_token: ${{ env.GIT_TOKEN }}
